// Mocks generated by Mockito 5.2.0 from annotations
// in sicpa_assessment_flutter/test/shared_mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sicpa_assessment_flutter/model/article_summary.dart' as _i5;
import 'package:sicpa_assessment_flutter/model/article_type.dart' as _i4;
import 'package:sicpa_assessment_flutter/model/popular_article_response.dart'
    as _i7;
import 'package:sicpa_assessment_flutter/model/search_response.dart' as _i6;
import 'package:sicpa_assessment_flutter/respository/article/article_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ArticleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRepository extends _i1.Mock implements _i2.ArticleRepository {
  MockArticleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> searchArticle(String? searchField) =>
      (super.noSuchMethod(Invocation.method(#searchArticle, [searchField]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> fetchPopularArticle(_i4.ArticleType? type) =>
      (super.noSuchMethod(Invocation.method(#fetchPopularArticle, [type]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}

/// A class which mocks [ArticleSummary].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleSummary extends _i1.Mock implements _i5.ArticleSummary {
  MockArticleSummary() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set title(String? _title) =>
      super.noSuchMethod(Invocation.setter(#title, _title),
          returnValueForMissingStub: null);
  @override
  set publishDate(String? _publishDate) =>
      super.noSuchMethod(Invocation.setter(#publishDate, _publishDate),
          returnValueForMissingStub: null);
  @override
  List<Object?> get props =>
      (super.noSuchMethod(Invocation.getter(#props), returnValue: <Object?>[])
          as List<Object?>);
}

/// A class which mocks [SearchResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchResponse extends _i1.Mock implements _i6.SearchResponse {
  MockSearchResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set docs(List<_i6.SearchResult>? _docs) =>
      super.noSuchMethod(Invocation.setter(#docs, _docs),
          returnValueForMissingStub: null);
  @override
  set meta(_i6.Meta? _meta) =>
      super.noSuchMethod(Invocation.setter(#meta, _meta),
          returnValueForMissingStub: null);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}

/// A class which mocks [PopularArticleResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularArticleResponse extends _i1.Mock
    implements _i7.PopularArticleResponse {
  MockPopularArticleResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set results(List<_i7.Article>? _results) =>
      super.noSuchMethod(Invocation.setter(#results, _results),
          returnValueForMissingStub: null);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
